apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/abandonedscope/dispatcher-service/k8s?ref=master

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: dispatcher-config

images:
- name: dispatcher-service
  newName: ghcr.io/AbandonedScope/dispatcher-service
  newTag: 05d65576fc91042305788d66147482913cd446df

replicas:
- count: 1
  name: dispatcher-service
