apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/abandonedscope/order-service/k8s?ref=master

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: order-config

images:
- name: order-service
  newName: ghcr.io/AbandonedScope/order-service
  newTag: c27d10c14d25105ba79a50e921331699fcc1169c

replicas:
- count: 1
  name: order-service
