apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/abandonedscope/catalog-service/k8s?ref=master
patchesStrategicMerge:
  - patch-env.yml
configMapGenerator:
  - name: catalog-config
    behavior: merge
    files:
      - application-staging.yml
images:
  - name: catalog-service
    newName: ghcr.io/abandonedscope/catalog-service
    newTag: latest
replicas:
  - name: catalog-service
    count: 2